### ISSUE TITLE
problems during installation: gyp WARN EACCES user "root" does not have permission...

### ISSUE THREAD

**Issue by carloscarcamo** [strongloop/strongloop#212]
I know this issue is repeated but I haven't seen any solution that fits with me, by the way it seems that strongloop is installed on my server but I have to do the following to use strongloop:

```
$ /usr/lib/node_modules/strongloop/bin/slc -v
strongloop v3.0.6 (node v0.12.2)
├── strong-arc@1.1.0
├── strong-build@1.0.3 (5a43a57)
├── strong-deploy@1.2.0 (1c78f8d)
├── strong-pm@3.1.9 (9579431)
├── strong-registry@1.1.4 (aab3dbb)
├── strong-start@1.0.3 (b23e63f)
├─┬ strong-supervisor@1.5.1 (d9364bd)
│ └── strong-agent@1.4.0
├── generator-loopback@1.9.0 (b90e9cd)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

I wonder if I will have problems in the future using strongloop CLI in this way, what do you recommend?

I'm using debian wheezy amd64, node v0.12.2 and npm v2.8.3.

Here is how I installed strongloop:

```
$sudo npm install -g strongloop
```

The output was: 

```
> heapdump@0.3.5 install /usr/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/.node-gyp"
make: Entering directory `/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  SOLINK_MODULE(target) Release/obj.target/addon.node: Finished
  COPY Release/addon.node
make: Leaving directory `/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/heapdump/build'
 
> strong-fork-syslog@1.2.3 install /usr/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog/.node-gyp"
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn ENOMEM
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at ChildProcess.spawn (child_process.js:1162:11)
gyp ERR! stack     at Object.exports.spawn (child_process.js:995:9)
gyp ERR! stack     at Gyp.spawn (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:186:26)
gyp ERR! stack     at runGyp (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:333:18)
gyp ERR! stack     at findConfigs (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:247:23)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:253:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
 ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/strongloop/node_modules/strong-supervisor/node_modules/strong-fork-syslog
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
 
> strong-agent@1.4.0 install /usr/lib/node_modules/strongloop/node_modules/strong-agent
> node-gyp rebuild || exit 0

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strongloop/node_modules/strong-agent/.node-gyp"
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack Error: spawn ENOMEM
gyp ERR! stack     at exports._errnoException (util.js:746:11)
gyp ERR! stack     at ChildProcess.spawn (child_process.js:1162:11)
gyp ERR! stack     at Object.exports.spawn (child_process.js:995:9)
gyp ERR! stack     at Gyp.spawn (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:186:26)
gyp ERR! stack     at runGyp (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:333:18)
gyp ERR! stack     at findConfigs (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:247:23)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:253:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/strongloop/node_modules/strong-agent
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
npm WARN optional dep failed, continuing strong-fork-syslog@1.2.3
-
> ws@0.4.32 install /usr/lib/node_modules/strongloop/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)
```

Can I use strongloop in this way or I have to do something to fix it?

Thanks in advance.

**Comment by sam-github** [comment]
We recommend installing like this: http://docs.strongloop.com/display/SL/Installing+StrongLoop#InstallingStrongLoop-Linux

If you must keep your /usr/local permissions locked down to root, and you install with sudo, then you need to use https://docs.npmjs.com/misc/config#unsafe-perm.

When run with sudo, npm drops permissions before running install scripts, making it impossible to compile node addons. It looks like you've run into this. However, the `ENOMEM` errors are strange. Either you are running on a VM with insufficient memory, or its a bug in npm/node where the wrong error number is being reported.

**Comment by carloscarcamo** [comment]
thanks :)
