### ISSUE TITLE
why npm test gives an error?

### ISSUE THREAD

**Issue by smartmouse** [strongloop/strongloop#245]
:~/teststrongloop/node_modules/strongloop$ npm test

> strongloop@5.0.0 pretest /home/nodebot/teststrongloop/node_modules/strongloop
> eslint --ignore-path .gitignore . && jscs .

/home/nodebot/teststrongloop/node_modules/strongloop/node_modules/eslint/lib/igno
            throw e;
                  ^
Error: Cannot read ignore file: .gitignore
Error: ENOENT, no such file or directory '.gitignore'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at loadIgnoreFile (/home/nodebot/teststrongloop/node_modules/strongloop/node_                  lib/ignored-paths.js:44:33)
    at Function.IgnoredPaths.load (/home/nodebot/teststrongloop/node_modules/stro                  ules/eslint/lib/ignored-paths.js:94:20)
    at CLIEngine.executeOnFiles (/home/nodebot/teststrongloop/node_modules/strong                  es/eslint/lib/cli-engine.js:309:41)
    at Object.cli.execute (/home/nodebot/teststrongloop/node_modules/strongloop/n                  int/lib/cli.js:179:95)

**Comment by rmg** [comment]
The `.gitignore` file is not included in the published tarball - `npm publish` turns it into the `.npmignore` file. Generally the tests are meant to be run on a git checkout.

**Comment by smartmouse** [comment]
Got it, works.  Some modules comes with the tests that work right away, looks like there are no standard way. Thanks anyways .
