### ISSUE TITLE
strongloop install fails

### ISSUE THREAD

**Issue by cebor** [strongloop/strongloop#253]
Got following errors while installing strongloop:

node v4.1
npm v3.3.3
osx 10.10.5
xcode clt v7

```syslog
npm install -g strongloop
npm WARN deprecated jsonstream@1.0.3: use JSONStream instead
npm WARN deprecated showdown@0.3.1: IMPORTANT hotfix
npm WARN deprecated react-tools@0.10.0: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
/usr/local/bin/slc -> /usr/local/lib/node_modules/strongloop/bin/slc.js
/usr/local/bin/lb-ng-doc -> /usr/local/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng-doc
/usr/local/bin/lb-ng -> /usr/local/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng

> bufferutil@1.2.1 install /usr/local/lib/node_modules/strongloop/node_modules/bufferutil
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node

> heapdump@0.3.7 install /usr/local/lib/node_modules/strongloop/node_modules/heapdump
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/addon.node

> modern-syslog@1.1.1 install /usr/local/lib/node_modules/strongloop/node_modules/modern-syslog
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/core/core.o
  SOLINK_MODULE(target) Release/core.node

> spawn-sync@1.0.13 postinstall /usr/local/lib/node_modules/strongloop/node_modules/spawn-sync
> node postinstall


> sqlite3@3.1.0 install /usr/local/lib/node_modules/strongloop/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/usr/local/lib/node_modules/strongloop/node_modules/sqlite3/lib/binding/node-v46-darwin-x64/node_sqlite3.node" is installed via remote

> strong-debugger@1.0.0 install /usr/local/lib/node_modules/strongloop/node_modules/strong-debugger
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/debugger/src/mutex-wrap.o
  CXX(target) Release/obj.target/debugger/src/debugger.o
  CXX(target) Release/obj.target/debugger/src/controller.o
  CXX(target) Release/obj.target/debugger/src/worker.o
  CXX(target) Release/obj.target/debugger/src/worker-bindings.o
  SOLINK_MODULE(target) Release/debugger.node

> strong-fork-syslog@1.2.3 install /usr/local/lib/node_modules/strongloop/node_modules/strong-fork-syslog
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:2:
../compat-inl.h:288:37: error: no member named 'StartCpuProfiling' in 'v8::CpuProfiler'; did you mean 'StartProfiling'?
  return isolate->GetCpuProfiler()->StartCpuProfiling(title, record_samples);
                                    ^~~~~~~~~~~~~~~~~
                                    StartProfiling
/Users/felix/.node-gyp/4.1.0/include/node/v8-profiler.h:201:8: note: 'StartProfiling' declared here
  void StartProfiling(Local<String> title, bool record_samples = false);
       ^
In file included from ../syslog.cc:2:
../compat-inl.h:294:37: error: no member named 'StopCpuProfiling' in 'v8::CpuProfiler'; did you mean 'StopProfiling'?
  return isolate->GetCpuProfiler()->StopCpuProfiling(title);
                                    ^~~~~~~~~~~~~~~~
                                    StopProfiling
/Users/felix/.node-gyp/4.1.0/include/node/v8-profiler.h:207:15: note: 'StopProfiling' declared here
  CpuProfile* StopProfiling(Local<String> title);
              ^
In file included from ../syslog.cc:2:
../compat-inl.h:310:55: error: no viable conversion from 'v8::Local<v8::String>' to 'v8::ActivityControl *'
  return isolate->GetHeapProfiler()->TakeHeapSnapshot(title);
                                                      ^~~~~
/Users/felix/.node-gyp/4.1.0/include/node/v8-profiler.h:487:24: note: passing argument to parameter 'control' here
      ActivityControl* control = NULL,
                       ^
3 errors generated.
make: *** [Release/obj.target/syslog/syslog.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/strongloop/node_modules/strong-fork-syslog
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
/usr/local/lib
└── (empty)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.0/bin/node" "/usr/local/bin/npm" "install" "-g" "strongloop"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! strong-fork-syslog@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strong-fork-syslog@1.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the strong-fork-syslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls strong-fork-syslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/felix/npm-debug.log
npm ERR! code 1
```

**Comment by rmg** [comment]
Same problem as in strongloop/strong-pm#278. npm@3 isn't respecting the optionalDependencies of nested dependencies when installing globally.

I've reported this upstream as npm/npm#9685, but in the mean time the solution is `npm install -g npm@2`.

**Comment by cebor** [comment]
With npm@2 the install process works, but i'm also getting some errors.

https://gist.github.com/cebor/7a68ce1eb45f537e9583

**Comment by rmg** [comment]
For an explanation of the errors in a successful install, see #248. 

As for the xcode-select errors, it looks like you haven't fully updated xcode or did not update the cli tools at the same time.
