### ISSUE TITLE
New Installs cant run pm because of Sqlite3 failure

### ISSUE THREAD

**Issue by HuemanF** [strongloop/strongloop#276]
slc pm
module.js:340
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v47-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by HuemanF** [comment]
node-**v11**-linux-x64/node_sqlite3.node' is present . if i rename folder  to v47 i get:

 slc pm
module.js:450
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:450:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

**Comment by Setogit** [comment]
@HuemanF What are your Node version and sqlite3 version you have here?
/usr/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/package.json

**Comment by rmg** [comment]
For anyone finding this later, `npm install -g strongloop` was done with node-v0.10.x and then node was upgraded to v5.x without reinstalling/rebuilding the binary dependencies. When `slc pm` was run under node-v5 it looked for the sqlite3 binary for node-v5, not v0.10 which is what was originally installed.

**Comment by HuemanF** [comment]
So if node is updated before installing strongloop there "should" be fine. I will try that.
 Thanks.
