### ISSUE TITLE
App is accessible when run using sl-pm,  but not when using  "sudo /sbin/initctl start strong-pm"

### ISSUE THREAD

**Issue by pvijeh** [strongloop/strongloop#284]
I have a loopback app running on a remote box. 

The app runs fine when I execute the "sl-pm" command.    I can access the api at IPADRESS:3001 as expected.   However,  when I try to run the app using the " sudo /sbin/initctl start strong-pm" command as the documentation suggest I get an error that looks like this in the logs:

pvijeh@places-api:/var/log/upstart$ sudo tail strong-pm.log -n 100
2015-12-30T20:37:14.488Z pid:2153 worker:22     at Connection.parseE (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:539:11)
2015-12-30T20:37:14.488Z pid:2153 worker:22     at Connection.parseMessage (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:366:17)
2015-12-30T20:37:14.488Z pid:2153 worker:22     at Socket.<anonymous> (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:105:22)
2015-12-30T20:37:14.488Z pid:2153 worker:22     at emitOne (events.js:78:13)
2015-12-30T20:37:14.488Z pid:2153 worker:22     at Socket.emit (events.js:170:7)
2015-12-30T20:37:14.488Z pid:2153 worker:22     at readableAddChunk (_stream_readable.js:147:16)
2015-12-30T20:37:14.488Z pid:2153 worker:22     at Socket.Readable.push (_stream_readable.js:111:10)
2015-12-30T20:37:14.489Z pid:2153 worker:22     at TCP.onread (net.js:524:20)
2015-12-30T20:37:14.571Z pid:1927 worker:0 ERROR supervisor worker id 22 (pid 2153) accidental exit with 1
2015-12-30T20:37:17.256Z pid:1927 worker:0 INFO supervisor started worker 24 (pid 2173)
2015-12-30T20:37:17.257Z pid:1927 worker:0 INFO supervisor resized to 2
2015-12-30T20:37:19.042Z pid:2173 worker:24 INFO strong-agent v2.0.2 profiling app 'placesAPI' pid '2173'
2015-12-30T20:37:19.056Z pid:2173 worker:24 INFO strong-agent[2173] started profiling agent
2015-12-30T20:37:19.929Z pid:2163 worker:23 INFO strong-agent not profiling, agent metrics requires a valid license.
2015-12-30T20:37:19.929Z pid:2163 worker:23 Please contact sales@strongloop.com for assistance.
2015-12-30T20:37:19.961Z pid:2163 worker:23 Web server listening at: http://0.0.0.0:3001
2015-12-30T20:37:19.970Z pid:2163 worker:23 Browse your REST API at http://0.0.0.0:3001/explorer
2015-12-30T20:37:20.049Z pid:2163 worker:23 Connection fails:  { [error: password authentication failed for user "pvijeh"]
2015-12-30T20:37:20.049Z pid:2163 worker:23   name: 'error',
2015-12-30T20:37:20.049Z pid:2163 worker:23   length: 95,
2015-12-30T20:37:20.049Z pid:2163 worker:23   severity: 'FATAL',
2015-12-30T20:37:20.049Z pid:2163 worker:23   code: '28P01',
2015-12-30T20:37:20.049Z pid:2163 worker:23   detail: undefined,
2015-12-30T20:37:20.049Z pid:2163 worker:23   hint: undefined,
2015-12-30T20:37:20.049Z pid:2163 worker:23   position: undefined,
2015-12-30T20:37:20.110Z pid:2163 worker:23   internalPosition: undefined,
2015-12-30T20:37:20.110Z pid:2163 worker:23   internalQuery: undefined,
2015-12-30T20:37:20.110Z pid:2163 worker:23   where: undefined,
2015-12-30T20:37:20.110Z pid:2163 worker:23   schema: undefined,
2015-12-30T20:37:20.110Z pid:2163 worker:23   table: undefined,
2015-12-30T20:37:20.111Z pid:2163 worker:23   column: undefined,
2015-12-30T20:37:20.111Z pid:2163 worker:23   dataType: undefined,
2015-12-30T20:37:20.111Z pid:2163 worker:23   constraint: undefined,
2015-12-30T20:37:20.111Z pid:2163 worker:23   file: 'auth.c',
2015-12-30T20:37:20.111Z pid:2163 worker:23   line: '304',
2015-12-30T20:37:20.111Z pid:2163 worker:23   routine: 'auth_failed' }
2015-12-30T20:37:20.111Z pid:2163 worker:23 It will be retried for the next request.
2015-12-30T20:37:20.111Z pid:2163 worker:23 events.js:142
2015-12-30T20:37:20.112Z pid:2163 worker:23       throw er; // Unhandled 'error' event
2015-12-30T20:37:20.112Z pid:2163 worker:23       ^
2015-12-30T20:37:20.112Z pid:2163 worker:23 error: password authentication failed for user "pvijeh"
2015-12-30T20:37:20.112Z pid:2163 worker:23     at Connection.parseE (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:539:11)
2015-12-30T20:37:20.112Z pid:2163 worker:23     at Connection.parseMessage (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:366:17)
2015-12-30T20:37:20.112Z pid:2163 worker:23     at Socket.<anonymous> (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:105:22)
2015-12-30T20:37:20.112Z pid:2163 worker:23     at emitOne (events.js:78:13)
2015-12-30T20:37:20.112Z pid:2163 worker:23     at Socket.emit (events.js:170:7)
2015-12-30T20:37:20.112Z pid:2163 worker:23     at readableAddChunk (_stream_readable.js:147:16)
2015-12-30T20:37:20.112Z pid:2163 worker:23     at Socket.Readable.push (_stream_readable.js:111:10)
2015-12-30T20:37:20.114Z pid:2163 worker:23     at TCP.onread (net.js:524:20)
2015-12-30T20:37:20.165Z pid:1927 worker:0 ERROR supervisor worker id 23 (pid 2163) accidental exit with 1
2015-12-30T20:37:22.384Z pid:1927 worker:0 INFO supervisor started worker 25 (pid 2183)
2015-12-30T20:37:22.384Z pid:1927 worker:0 INFO supervisor resized to 2
2015-12-30T20:37:25.047Z pid:2183 worker:25 INFO strong-agent v2.0.2 profiling app 'placesAPI' pid '2183'
2015-12-30T20:37:25.071Z pid:2183 worker:25 INFO strong-agent[2183] started profiling agent
2015-12-30T20:37:25.296Z pid:2173 worker:24 INFO strong-agent not profiling, agent metrics requires a valid license.
2015-12-30T20:37:25.296Z pid:2173 worker:24 Please contact sales@strongloop.com for assistance.
2015-12-30T20:37:25.431Z pid:2173 worker:24 Web server listening at: http://0.0.0.0:3001
2015-12-30T20:37:25.431Z pid:2173 worker:24 Browse your REST API at http://0.0.0.0:3001/explorer
2015-12-30T20:37:25.821Z pid:2173 worker:24 Connection fails:  { [error: password authentication failed for user "pvijeh"]
2015-12-30T20:37:25.822Z pid:2173 worker:24   name: 'error',
2015-12-30T20:37:25.822Z pid:2173 worker:24   length: 95,
2015-12-30T20:37:25.822Z pid:2173 worker:24   severity: 'FATAL',
2015-12-30T20:37:25.822Z pid:2173 worker:24   code: '28P01',
2015-12-30T20:37:25.822Z pid:2173 worker:24   detail: undefined,
2015-12-30T20:37:25.822Z pid:2173 worker:24   hint: undefined,
2015-12-30T20:37:25.822Z pid:2173 worker:24   position: undefined,
2015-12-30T20:37:25.822Z pid:2173 worker:24   internalPosition: undefined,
2015-12-30T20:37:25.822Z pid:2173 worker:24   internalQuery: undefined,
2015-12-30T20:37:25.823Z pid:2173 worker:24   where: undefined,
2015-12-30T20:37:25.823Z pid:2173 worker:24   schema: undefined,
2015-12-30T20:37:25.823Z pid:2173 worker:24   table: undefined,
2015-12-30T20:37:25.823Z pid:2173 worker:24   column: undefined,
2015-12-30T20:37:25.823Z pid:2173 worker:24   dataType: undefined,
2015-12-30T20:37:25.823Z pid:2173 worker:24   constraint: undefined,
2015-12-30T20:37:25.823Z pid:2173 worker:24   file: 'auth.c',
2015-12-30T20:37:25.823Z pid:2173 worker:24   line: '304',
2015-12-30T20:37:25.823Z pid:2173 worker:24   routine: 'auth_failed' }
2015-12-30T20:37:25.823Z pid:2173 worker:24 It will be retried for the next request.
2015-12-30T20:37:25.841Z pid:2173 worker:24 events.js:142
2015-12-30T20:37:25.841Z pid:2173 worker:24       throw er; // Unhandled 'error' event
2015-12-30T20:37:25.841Z pid:2173 worker:24       ^
2015-12-30T20:37:25.841Z pid:2173 worker:24 error: password authentication failed for user "pvijeh"
2015-12-30T20:37:25.842Z pid:2173 worker:24     at Connection.parseE (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:539:11)
2015-12-30T20:37:25.842Z pid:2173 worker:24     at Connection.parseMessage (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:366:17)
2015-12-30T20:37:25.842Z pid:2173 worker:24     at Socket.<anonymous> (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:105:22)
2015-12-30T20:37:25.842Z pid:2173 worker:24     at emitOne (events.js:78:13)
2015-12-30T20:37:25.842Z pid:2173 worker:24     at Socket.emit (events.js:170:7)
2015-12-30T20:37:25.842Z pid:2173 worker:24     at readableAddChunk (_stream_readable.js:147:16)
2015-12-30T20:37:25.842Z pid:2173 worker:24     at Socket.Readable.push (_stream_readable.js:111:10)
2015-12-30T20:37:25.842Z pid:2173 worker:24     at TCP.onread (net.js:524:20)
2015-12-30T20:37:25.900Z pid:1927 worker:0 ERROR supervisor worker id 24 (pid 2173) accidental exit with 1
2015-12-30T20:37:28.100Z pid:1927 worker:0 INFO supervisor started worker 26 (pid 2198)
sl-pm.js(2418): StrongLoop PM v5.1.0 (API v6.1.0) on port `8701`
sl-pm.js(2418): Base folder `/var/lib/strong-pm`
sl-pm.js(2418): Applications on port `3000 + service ID`
Browse your REST API at http://127.0.0.1:8701/explorer
sl-pm.js(2650): StrongLoop PM v5.1.0 (API v6.1.0) on port `8701`
sl-pm.js(2650): Base folder `/var/lib/strong-pm`
sl-pm.js(2650): Applications on port `3000 + service ID`
Browse your REST API at http://127.0.0.1:8701/explorer

**Comment by sam-github** [comment]
```
2015-12-30T20:37:20.049Z pid:2163 worker:23 Connection fails: { [error: password authentication failed for user "pvijeh"]
2015-12-30T20:37:20.112Z pid:2163 worker:23 at Connection.parseE (/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451507487151/node_modules/pg/lib/connection.js:539:11)
```

Your app is exiting (and being restarted) because its failing to auth against postgres, any idea why that is?

**Comment by pvijeh** [comment]
Yes,  somehow the server/datasource.json file has an old password for the postgres user.  I can't update this through a deploy-- because deploying fails with an error like this for some reason:

Error connecting to server: { [Error: connect ETIMEDOUT 198.105.244.228:8701]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '198.105.244.228',
  port: 8701 }



But,  why would the app run when using "sl-pm" command,  and not when using " sudo /sbin/initctl start strong-pm"  ?

**Comment by rmg** [comment]
@pvijeh when you run pm with `sl-pm` it is running as your current user and using `~/.strong-pm` as its base directory. When you run `sudo start strong-pm` it is starting a service running as the `strong-pm` user and using `/var/lib/strong-pm` as the base directory. They are completely separate and apps deployed to one are not deployed to the other. Additionally, if you try running both instances at the same time one of them will fail because they would both be trying to use TCP port 8701.

To clear the bad deployment I suggest `sudo stop strong-pm && sudo rm -rf /var/lib/strong-pm/* && sudo start strong-pm`.

**Comment by rmg** [comment]
Closing as resolved.
