### ISSUE TITLE
slc deploy does not deploy changes to app 

### ISSUE THREAD

**Issue by pvijeh** [strongloop/strongloop#285]
I am building a loopback app that is deployed using strongloop to a remote box running strong-pm. 

I have made some changes to my local app,  but when I deploy them to the remote box using: 

slc build 

followed by 

slc deploy http://IPADDRESS

the changes are not reflected on the  app running on the remote box.  

Even after rebooting the remote box using 'sudo reboot'  or restarting strong-pm using 'sudo /sbin/initctl stop strong-pm' followed by ''sudo /sbin/initctl stop strong-pm'  the changes are not reflected in the remote app. 

Any ideas whats wrong?

**Comment by rmg** [comment]
@pvijeh what is in `/var/log/upstart/strong-pm.log`?

**Comment by pvijeh** [comment]
I have pasted in the last 100 lines of that log below.

Notably there is an error connecting to postgres which i can fix by
directly modifying the files on the server located here:

pvijeh@places-api
:/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451600828087/server$

the reason for that error is the new password saved in the local version of
the app is not being reflected in the remote version of the app.





pvijeh@places-api:/var/log/upstart$ sudo tail -n 100 strong-pm.log
2015-12-31T22:30:04.670Z pid:1585 worker:26     at Socket.<anonymous>
(/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451600828087/node_modules/pg/lib/connection.js:105:22)
2015-12-31T22:30:04.670Z pid:1585 worker:26     at emitOne (events.js:78:13)
2015-12-31T22:30:04.670Z pid:1585 worker:26     at Socket.emit
(events.js:170:7)
2015-12-31T22:30:04.670Z pid:1585 worker:26     at readableAddChunk
(_stream_readable.js:147:16)
2015-12-31T22:30:04.670Z pid:1585 worker:26     at Socket.Readable.push
(_stream_readable.js:111:10)
2015-12-31T22:30:04.670Z pid:1585 worker:26     at TCP.onread
(net.js:524:20)
2015-12-31T22:30:04.681Z pid:1307 worker:0 ERROR supervisor worker id 26
(pid 1585) accidental exit with 1
2015-12-31T22:30:06.013Z pid:1597 worker:27 INFO strong-agent not
profiling, agent metrics requires a valid license.
2015-12-31T22:30:06.013Z pid:1597 worker:27 Please contact
sales@strongloop.com for assistance.
2015-12-31T22:30:06.039Z pid:1597 worker:27 Web server listening at:
http://0.0.0.0:3001
2015-12-31T22:30:06.042Z pid:1597 worker:27 Browse your REST API at
http://0.0.0.0:3001/explorer
2015-12-31T22:30:06.102Z pid:1597 worker:27 Connection fails:  { [error:
password authentication failed for user "pvijeh"]
2015-12-31T22:30:06.102Z pid:1597 worker:27   name: 'error',
2015-12-31T22:30:06.102Z pid:1597 worker:27   length: 95,
2015-12-31T22:30:06.103Z pid:1597 worker:27   severity: 'FATAL',
2015-12-31T22:30:06.103Z pid:1597 worker:27   code: '28P01',
2015-12-31T22:30:06.103Z pid:1597 worker:27   detail: undefined,
2015-12-31T22:30:06.103Z pid:1597 worker:27   hint: undefined,
2015-12-31T22:30:06.103Z pid:1597 worker:27   position: undefined,
2015-12-31T22:30:06.103Z pid:1597 worker:27   internalPosition: undefined,
2015-12-31T22:30:06.103Z pid:1597 worker:27   internalQuery: undefined,
2015-12-31T22:30:06.103Z pid:1597 worker:27   where: undefined,
2015-12-31T22:30:06.103Z pid:1597 worker:27   schema: undefined,
2015-12-31T22:30:06.103Z pid:1597 worker:27   table: undefined,
2015-12-31T22:30:06.104Z pid:1597 worker:27   column: undefined,
2015-12-31T22:30:06.104Z pid:1597 worker:27   dataType: undefined,
2015-12-31T22:30:06.104Z pid:1597 worker:27   constraint: undefined,
2015-12-31T22:30:06.104Z pid:1597 worker:27   file: 'auth.c',
2015-12-31T22:30:06.104Z pid:1597 worker:27   line: '304',
2015-12-31T22:30:06.104Z pid:1597 worker:27   routine: 'auth_failed' }
2015-12-31T22:30:06.106Z pid:1597 worker:27 It will be retried for the next
request.
2015-12-31T22:30:06.119Z pid:1597 worker:27 events.js:142
2015-12-31T22:30:06.121Z pid:1597 worker:27       throw er; // Unhandled
'error' event
2015-12-31T22:30:06.123Z pid:1597 worker:27       ^
2015-12-31T22:30:06.124Z pid:1597 worker:27 error: password authentication
failed for user "pvijeh"
2015-12-31T22:30:06.125Z pid:1597 worker:27     at Connection.parseE
(/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451600828087/node_modules/pg/lib/connection.js:539:11)
2015-12-31T22:30:06.125Z pid:1597 worker:27     at Connection.parseMessage
(/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451600828087/node_modules/pg/lib/connection.js:366:17)
2015-12-31T22:30:06.126Z pid:1597 worker:27     at Socket.<anonymous>
(/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451600828087/node_modules/pg/lib/connection.js:105:22)
2015-12-31T22:30:06.126Z pid:1597 worker:27     at emitOne (events.js:78:13)
2015-12-31T22:30:06.126Z pid:1597 worker:27     at Socket.emit
(events.js:170:7)
2015-12-31T22:30:06.127Z pid:1597 worker:27     at readableAddChunk
(_stream_readable.js:147:16)
2015-12-31T22:30:06.127Z pid:1597 worker:27     at Socket.Readable.push
(_stream_readable.js:111:10)
2015-12-31T22:30:06.128Z pid:1597 worker:27     at TCP.onread
(net.js:524:20)
2015-12-31T22:30:06.153Z pid:1307 worker:0 ERROR supervisor worker id 27
(pid 1597) accidental exit with 1
2015-12-31T22:30:06.850Z pid:1307 worker:0 INFO supervisor started worker
28 (pid 1613)
2015-12-31T22:30:07.473Z pid:1613 worker:28 INFO strong-agent v2.0.2
profiling app 'placesAPI' pid '1613'
2015-12-31T22:30:07.497Z pid:1613 worker:28 INFO strong-agent[1613] started
profiling agent
2015-12-31T22:30:09.064Z pid:1307 worker:0 INFO supervisor started worker
29 (pid 1618)
2015-12-31T22:30:09.064Z pid:1307 worker:0 INFO supervisor resized to 2
2015-12-31T22:30:10.111Z pid:1618 worker:29 INFO strong-agent v2.0.2
profiling app 'placesAPI' pid '1618'
2015-12-31T22:30:10.120Z pid:1618 worker:29 INFO strong-agent[1618] started
profiling agent
2015-12-31T22:30:11.008Z pid:1613 worker:28 INFO strong-agent not
profiling, agent metrics requires a valid license.
2015-12-31T22:30:11.008Z pid:1613 worker:28 Please contact
sales@strongloop.com for assistance.
2015-12-31T22:30:11.029Z pid:1613 worker:28 Web server listening at:
http://0.0.0.0:3001
2015-12-31T22:30:11.030Z pid:1613 worker:28 Browse your REST API at
http://0.0.0.0:3001/explorer
2015-12-31T22:30:11.127Z pid:1613 worker:28 Connection fails:  { [error:
password authentication failed for user "pvijeh"]
2015-12-31T22:30:11.127Z pid:1613 worker:28   name: 'error',
2015-12-31T22:30:11.128Z pid:1613 worker:28   length: 95,
2015-12-31T22:30:11.128Z pid:1613 worker:28   severity: 'FATAL',
2015-12-31T22:30:11.128Z pid:1613 worker:28   code: '28P01',
2015-12-31T22:30:11.128Z pid:1613 worker:28   detail: undefined,
2015-12-31T22:30:11.128Z pid:1613 worker:28   hint: undefined,
2015-12-31T22:30:11.128Z pid:1613 worker:28   position: undefined,
2015-12-31T22:30:11.128Z pid:1613 worker:28   internalPosition: undefined,
2015-12-31T22:30:11.128Z pid:1613 worker:28   internalQuery: undefined,
2015-12-31T22:30:11.129Z pid:1613 worker:28   where: undefined,
2015-12-31T22:30:11.132Z pid:1613 worker:28   schema: undefined,
2015-12-31T22:30:11.132Z pid:1613 worker:28   table: undefined,
2015-12-31T22:30:11.132Z pid:1613 worker:28   column: undefined,
2015-12-31T22:30:11.132Z pid:1613 worker:28   dataType: undefined,
2015-12-31T22:30:11.132Z pid:1613 worker:28   constraint: undefined,
2015-12-31T22:30:11.132Z pid:1613 worker:28   file: 'auth.c',
2015-12-31T22:30:11.133Z pid:1613 worker:28   line: '304',
2015-12-31T22:30:11.133Z pid:1613 worker:28   routine: 'auth_failed' }
2015-12-31T22:30:11.133Z pid:1613 worker:28 It will be retried for the next
request.
2015-12-31T22:30:11.143Z pid:1613 worker:28 events.js:142
2015-12-31T22:30:11.144Z pid:1613 worker:28       throw er; // Unhandled
'error' event
2015-12-31T22:30:11.145Z pid:1613 worker:28       ^
2015-12-31T22:30:11.146Z pid:1613 worker:28 error: password authentication
failed for user "pvijeh"
2015-12-31T22:30:11.146Z pid:1613 worker:28     at Connection.parseE
(/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451600828087/node_modules/pg/lib/connection.js:539:11)
2015-12-31T22:30:11.147Z pid:1613 worker:28     at Connection.parseMessage
(/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451600828087/node_modules/pg/lib/connection.js:366:17)
2015-12-31T22:30:11.148Z pid:1613 worker:28     at Socket.<anonymous>
(/var/lib/strong-pm/svc/1/work/c2965638b5008bcbab48164b037705b26af0d3aa.1451600828087/node_modules/pg/lib/connection.js:105:22)
2015-12-31T22:30:11.149Z pid:1613 worker:28     at emitOne (events.js:78:13)
2015-12-31T22:30:11.149Z pid:1613 worker:28     at Socket.emit
(events.js:170:7)
2015-12-31T22:30:11.160Z pid:1613 worker:28     at readableAddChunk
(_stream_readable.js:147:16)
2015-12-31T22:30:11.162Z pid:1613 worker:28     at Socket.Readable.push
(_stream_readable.js:111:10)
2015-12-31T22:30:11.163Z pid:1613 worker:28     at TCP.onread
(net.js:524:20)
2015-12-31T22:30:11.174Z pid:1307 worker:0 ERROR supervisor worker id 28
(pid 1613) accidental exit with 1
2015-12-31T22:30:13.402Z pid:1307 worker:0 INFO supervisor started worker
30 (pid 1632)
2015-12-31T22:30:13.404Z pid:1307 worker:0 INFO supervisor resized to 2
2015-12-31T22:30:13.625Z pid:1618 worker:29 INFO strong-agent not
profiling, agent metrics requires a valid license.
2015-12-31T22:30:13.625Z pid:1618 worker:29 Please contact
sales@strongloop.com for assistance.
2015-12-31T22:30:13.648Z pid:1618 worker:29 Web server listening at:
http://0.0.0.0:3001
2015-12-31T22:30:13.648Z pid:1618 worker:29 Browse your REST API at
http://0.0.0.0:3001/explorer
2015-12-31T22:30:14.344Z pid:1632 worker:30 INFO strong-agent v2.0.2
profiling app 'placesAPI' pid '1632'
2015-12-31T22:30:14.344Z pid:1632 worker:30 INFO strong-agent[1632] started
profiling agent
2015-12-31T22:30:18.597Z pid:1632 worker:30 INFO strong-agent not
profiling, agent metrics requires a valid license.
2015-12-31T22:30:18.600Z pid:1632 worker:30 Please contact
sales@strongloop.com for assistance.
2015-12-31T22:30:18.638Z pid:1632 worker:30 Web server listening at:
http://0.0.0.0:3001
2015-12-31T22:30:18.639Z pid:1632 worker:30 Browse your REST API at
http://0.0.0.0:3001/explorer

**Comment by pvijeh** [comment]
Its as if it is deploying some old version of the app from somewhere.

**Comment by pvijeh** [comment]
I tried completely deleting the deploy branch and then rebuilding the app for deployment.  This did not work and the problem persists. 

Here is what I did:

$ git checkout deploy 
$ rm -rf * 
$ git checkout master
$slc build
$slc deploy 

still an old version of the app gets deployed to the server

**Comment by pvijeh** [comment]
Is there a way that I can ensure slc is deploying using git and not a tar file?

**Comment by pvijeh** [comment]
I made a writeup of the problem on stackoverflow here: 

http://stackoverflow.com/questions/34552333/changes-to-loopback-app-not-being-deployed-via-slc-deploy

**Comment by rmg** [comment]
From `slc deploy --help`:
> Default behaviour is to deploy to `http://localhost:8701`. An npm package from
> the parent directory is deployed, if one is found for the current application
> version, otherwise the git branch `deploy` is deployed.

This means if you have a `.tgz` file in the parent directory that was created by running `slc build` then it will deploy that. If it doesn't find such a file, it will deploy your `deploy` branch, using git.

**Comment by rmg** [comment]
> I made a writeup of the problem on stackoverflow here:
> http://stackoverflow.com/questions/34552333/changes-to-loopback-app-not-being-deployed-via-slc-deploy

You have also posted the same general problem in other places:
 * http://stackoverflow.com/questions/34537296/strongloop-pm-app-wont-run-when-using-sudo-sbin-initctl-start-strong-pm-comm
 * http://stackoverflow.com/questions/34520137/strongloop-process-manager-error-password-authentication-for-user-user
 * http://stackoverflow.com/questions/34502741/strongloop-slc-clt-error-failed-with-error-read-etimedout
 * #284 
 * #283 
 * #280 
 * strongloop/strong-pm#303
 * strongloop/strong-pm#301

It is very difficult to keep track of all of these posts and impossible to tell which one you are expecting to find your answer on.

@pvijeh Please pick **one** and close/delete all the others so we can focus on solving the problem instead of tracking tickets.

**Comment by dmastag** [comment]
I know this is a old post but for anyone getting this issue I just encountered the same problem.
Finally I used slc arc and tried to Build from there.

Make sure that the "Fully qualified path to archive" has a correct value
It should be something like  ../project-1.0.0.tgz

**Comment by rmg** [comment]
This issue appears to be dead or resolved elsewhere.
