### ISSUE TITLE
slc loopback:swagger throwing "Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by JacquesPerrault** [strongloop/strongloop#299]
I wrote a swagger definition, then downloaded it as JSON via "file download" at editor.swagger.io (file below).  

When issuing `slc loopback:swagger` on that file, slc throws *Cannot read property 'toLowerCase' of undefined*.  I've tried on Windows and Mac, same error.

```
{
    "swagger": "2.0",
    "info": {
        "version": "0.0.1",
        "title": "VerseU APIs"
    },
    "host": "localhost:10010",
    "basePath": "/",
    "schemes": [
        "http",
        "https"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/search/messages": {
            "x-swagger-router-controller": "searchMessages",
            "post": {
                "summary": "Returns messages for the authenticated user",
                "description": "",
                "operationId": "searchMessages",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "description": "Filters to use as part of the search",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Filter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "$ref": "#/definitions/HelloWorldResponse"
                        }
                    },
                    "default": {
                        "description": "Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Values": {
            "type": "object",
            "required": [
                "key",
                "value"
            ],
            "properties": {
                "key": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "Filter": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "string"
                },
                "tags": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "string"
                },
                "startDate": {
                    "type": "string"
                },
                "endDate": {
                    "type": "string"
                },
                "minSentiment": {
                    "type": "integer"
                },
                "maxSentiment": {
                    "type": "integer"
                },
                "arbitraryParams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Values"
                    }
                }
            }
        },
        "HelloWorldResponse": {
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "ErrorResponse": {
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}
```

**Comment by raymondfeng** [comment]
Can you post the full stacktrace?

**Comment by JacquesPerrault** [comment]
doh!  sorry, here it is:

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at V2Generator.getOperations (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-swagger\lib\codegen\generator-v2.js:114:33)
    at V2Generator.BaseGenerator.generateRemoteMethods (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-swagger\lib\codegen\generator-base.js:90:25)
    at Object.exports.generateRemoteMethods (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\loopback-swagger\index.js:25:29)
    at C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\swagger\spec-loader.js:144:30
    at C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\node_modules\async\lib\async.js:209:22)
    at C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\swagger\spec-loader.js:143:13
    at C:\Users\IBM_ADMIN\AppData\Roaming\npm\node_modules\strongloop\node_modules\generator-loopback\swagger\spec-loader.js:118:7
    at doNTCallback0 (node.js:419:9)

```

**Comment by raymondfeng** [comment]
Was the swagger file generated by a tool? It has the `x-swagger-router-controller` extension under the path key:

```
"paths": {
        "/search/messages": {
            "x-swagger-router-controller": "searchMessages",
            "post": {
```

**Comment by JacquesPerrault** [comment]
I coded the entire .yaml by hand, it looks like:
```
  /messages/send:
    x-swagger-router-controller: messagesSend
    post:
```

**Comment by raymondfeng** [comment]
Can you try the latest version? My PR https://github.com/strongloop/loopback-swagger/issues/30 should fix the issue.

**Comment by JacquesPerrault** [comment]
Will do!  I'm on my way to the airport, and will pull as time allows; I may not be able to get to it until tomorrow.

**Comment by sam-github** [comment]
@JacquesPerrault is this good now? can we close?

**Comment by JacquesPerrault** [comment]
Yes, all set, thanks!
