### ISSUE TITLE
Error executing `slc loopback`

### ISSUE THREAD

**Issue by apinnecke** [strongloop/strongloop#315]
Hey all,

I've got an error executing `slc loopback`. It doesn't matter weather I choose v2.x or v3.x.

These are my versions and my output:
```
$ slc loopback

     _-----_
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Let's create a LoopBack │
   `---------´   │       application!       │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What's the name of your application? fancy-project
? Enter name of the directory to contain the project: fancy-project
     info change the working directory to fancy-project

? What kind of application do you have in mind? api-server (A LoopBack API server with local User auth)
? Which version of LoopBack would you like to use? 2.x
/usr/local/lib/node_modules/strongloop/node_modules/loopback-workspace/server/connector.js:204
              f.data.devDependencies['loopback'] ||
                                    ^

TypeError: Cannot read property 'loopback' of undefined
    at /usr/local/lib/node_modules/strongloop/node_modules/loopback-workspace/server/connector.js:204:37
    at /usr/local/lib/node_modules/strongloop/node_modules/loopback-workspace/node_modules/async/lib/async.js:52:16
    at Immediate.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/loopback-workspace/node_modules/async/lib/async.js:1206:34)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
$ node -v
v6.3.1
$ npm -v
3.10.3
$ npm -g ls | grep strongloop
├─┬ strongloop@6.0.1
│ │ └─┬ strongloop-license@1.5.2
$

```

Any ideas what's the problem here?

**Comment by apinnecke** [comment]
Seems like the problem got fixed here: https://github.com/strongloop/loopback-workspace/commit/fef090d35ee71843afc9c06ff96e5a056f8fe02e. Applying this change manually fixes the issue for me, so basically here is just an update of the `loopback-workspace` required.
