### ISSUE TITLE
Fails to install on Node 6/NPM 3 with `" Cannot find module 'events/' "` error

### ISSUE THREAD

**Issue by persimmons** [strongloop/strongloop#329]
Hello,

I installed Strongloop globally with `npm i -g strongloop` and got a critical failure in the install scripts.  This failure happens on strongloop@6.0.3, strongloop@6.0.2, strongloop@5 on node 6.7.0/npm 3.10.3/OSX 10.11.6.

The install fails with this error:

```
> strong-mesh-client@1.6.3 install /Users/kjackson/.nvm/versions/node/v6.7.0/lib/node_modules/strongloop/node_modules/strong-mesh-client
> node proxy/build-client.js

module.js:457
    throw err;
    ^

Error: Cannot find module 'events/'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/Users/kjackson/.nvm/versions/node/v6.7.0/lib/node_modules/strongloop/node_modules/browserify/lib/builtins.js:11:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
/Users/kjackson/.nvm/versions/node/v6.7.0/lib
```

I ran into this failure initially running Node v6.4.0, so I updated / wiped my globally installed modules with Node 6.7 and NPM 3.10.3, but the problem persists.  This failure prevents the install from finishing, so I am unable to use the slc binary.

**Comment by rmg** [comment]
Closing since this is similar to #337 which was resolved recently. Please re-open if you are still seeing this issue.
