### ISSUE TITLE
Installation succeeds but has many compiler errors

### ISSUE THREAD

**Issue by piyuaryan** [strongloop/strongloop#338]
I'm unable to install strong loop using latest version of Node(v7.7.2) and NPM(4.1.2).
Please help.

```
$ npm install -g strongloop
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/lb-ng -> /usr/local/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng.js
/usr/local/bin/slc -> /usr/local/lib/node_modules/strongloop/bin/slc.js

> strong-debugger@1.0.0 install /usr/local/lib/node_modules/strongloop/node_modules/strong-debugger
> node-gyp rebuild

  CXX(target) Release/obj.target/debugger/src/mutex-wrap.o
  CXX(target) Release/obj.target/debugger/src/debugger.o
  CXX(target) Release/obj.target/debugger/src/controller.o
../src/controller.cc:189:31: error: too few arguments to function call, single argument 'isolate' was not specified
  Debug::ProcessDebugMessages();
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/devil/.node-gyp/7.7.2/include/node/v8-debug.h:239:3: note: 'ProcessDebugMessages' declared here
  static void ProcessDebugMessages(Isolate* isolate);
  ^
../src/controller.cc:196:42: error: too few arguments to function call, expected 2, have 1
  Debug::SetMessageHandler(MessageHandler);
  ~~~~~~~~~~~~~~~~~~~~~~~~               ^
/Users/devil/.node-gyp/7.7.2/include/node/v8-debug.h:173:3: note: 'SetMessageHandler' declared here
  static void SetMessageHandler(Isolate* isolate, MessageHandler handler);
  ^
../src/controller.cc:205:31: error: too few arguments to function call, single argument 'isolate' was not specified
  Debug::ProcessDebugMessages();
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/devil/.node-gyp/7.7.2/include/node/v8-debug.h:239:3: note: 'ProcessDebugMessages' declared here
  static void ProcessDebugMessages(Isolate* isolate);
  ^
../src/controller.cc:206:29: error: too few arguments to function call, expected 2, have 1
  Debug::SetMessageHandler(0);
  ~~~~~~~~~~~~~~~~~~~~~~~~  ^
/Users/devil/.node-gyp/7.7.2/include/node/v8-debug.h:173:3: note: 'SetMessageHandler' declared here
  static void SetMessageHandler(Isolate* isolate, MessageHandler handler);
  ^
4 errors generated.
make: *** [Release/obj.target/debugger/src/controller.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/Cellar/node/7.7.2/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/strongloop/node_modules/strong-debugger
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
/usr/local/lib
└── strongloop@6.0.3 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strong-debugger@1.0.0 (node_modules/strongloop/node_modules/strong-debugger):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strong-debugger@1.0.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by rmg** [comment]
@piyuaryan this is an optional dependency so the build failure should only have been treated as a warning. The output looks like it succeeds at the end:
```
/usr/local/lib
└── strongloop@6.0.3 
```

Does `slc --version` work?

**Comment by piyuaryan** [comment]
Well, slc --version works, but while installation it gave me error and build (make) failed constantly.

Anyway, my server is working now so I'm not looking for urgent fixes.
Thanks.

**Comment by cdjim** [comment]
I encountered the exact same compiler errors, though SLC works after installation.

Any further update on how to solve the above errors?
