### ISSUE TITLE
Can't install strongloop on GNU/Linux Debian

### ISSUE THREAD

**Issue by konkor** [strongloop/strongloop#354]
When I'm trying to install strongloop on Debian, I have this:
```
# npm install -g strongloop
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated ejs@1.0.0: Critical security bugs fixed in 2.5.5
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated sprintf@0.1.1: The sprintf package is deprecated in favor of sprintf-js.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/bin/lb-ng -> /usr/lib/node_modules/strongloop/node_modules/loopback-sdk-angular-cli/bin/lb-ng.js
/usr/bin/slc -> /usr/lib/node_modules/strongloop/bin/slc.js

> heapdump@0.3.9 install /usr/lib/node_modules/strongloop/node_modules/heapdump
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strongloop/node_modules/heapdump/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/strongloop/node_modules/heapdump/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strongloop/node_modules/heapdump/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/strongloop/node_modules/heapdump/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strongloop/node_modules/heapdump/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/strongloop/node_modules/heapdump/.node-gyp/8.9.4"
...
```
Stable Nodejs is installed from official repository via _apt-get install nodejs_ globally. So node_modules in the `/usr/lib/node_modules` folder not in the local folder.
```
# node -v
v8.9.4
# npm -v
5.6.0
# ls /usr/lib/node_modules/
express  express-generator  npm  strong-cli  strongloop  undefined  yo
```
I have googled a bit and tried _# npm install -g strongloop --allow-root_ the same result. Also I have tried:
```
# npm install --unsafe-perm -g strongloop
...
strong-agent.target.mk:105: recipe for target 'Release/obj.target/strong-agent/src/strong-agent.o' failed
make: *** [Release/obj.target/strong-agent/src/strong-agent.o] Error 1
make: Leaving directory '/usr/lib/node_modules/strongloop/node_modules/strong-agent/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-0.bpo.2-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/strongloop/node_modules/strong-agent
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
...
debugger.target.mk:99: recipe for target 'Release/obj.target/debugger/src/controller.o' failed
make: *** [Release/obj.target/debugger/src/controller.o] Error 1
make: Leaving directory '/usr/lib/node_modules/strongloop/node_modules/strong-debugger/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.0-0.bpo.2-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/strongloop/node_modules/strong-debugger
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
...
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strong-debugger@1.0.0 (node_modules/strongloop/node_modules/strong-debugger):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strong-debugger@1.0.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
It looks like working but without some additional dependencies and strong-debuger. Is it normal?

**So what about this depreciation warnings and security issues? Strongloop is so vulnerable? **

**Comment by jitbasemartin** [comment]
I don't know if it's a good fix but it works for me

```
sudo npm uninstall -g strongloop
git clone https://github.com/strongloop/strongloop.git
cd strongloop/
git checkout snyk-fix-78e89946 # Check if a more up to date version is available
sudo npm install -g
```

My setup:
```
> lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

> node --version
v8.9.4

> npm --version
5.6.0
```

**Comment by jrandria** [comment]
For me: 

```
npm uninstall -g strongloop
npm install -g strongloop
```


works well in windows
